from selenium import webdriver
from time import sleep 
from selenium.webdriver.common.keys import Keys
url = "https://facebook.com/"
d = webdriver.Chrome()
d.get(url)
usr = str(input("Usuário:\n"))
pw = str(input("Senha:\n"))
target = str(input("Digite o nome da pessoa para quem você quer enviar a mensagem: \n"))
sleep(2)

target_user = d.find_element_by_xpath('//*[@id="email"]')
target_pw = d.find_element_by_xpath('//*[@id="pass"]')
target_user.click()
sleep(2)
target_user.send_keys(usr)
sleep(2)
target_pw.send_keys(pw)
sleep(2)
log_in = d.find_element_by_xpath('//*[@id="u_0_b"]')
sleep(1)
log_in.click()
sleep(3)
open_chat = d.find_element_by_xpath('//*[@id="u_0_a"]/div[2]/div[2]')
open_chat.click()
see_everything = d.find_element_by_xpath('//*[@id="MercuryJewelFooter"]/div/a[1]')
see_everything.click()
sleep(5)
search_People = d.find_element_by_class_name('_58ak')
search_People.click()
sleep(2)
search_People.send_keys(target)
search_People.click()
sleep(5)
search_People.send_keys(Keys.ENTER)
sleep(2)
select_People = d.find_elements_by_xpath('//*[@id="js_v"]/div/div/div[1]/span[1]/div/div/ul/li[1]/a/div/div[2]/div/div')
print(select_People)
select_People.click()
sleep(2)
message_Box = d.find_element_by_xpath('//*[@id="cch_f3102302c832a"]/div[2]/div[2]/div[2]/div/div[4]/div/div/div[1]/div/div[2]/div/div/div/div')
message_Box.click()
message_Box.send_keys("Malz, mano! Tô enviando essa mensagem do meu bot só pra testar")
sleep(1)
sendIt = d.find_element_by_xpath('//*[@id="js_14z"]')
sendIt.click()
